### ISSUE TITLE
Erro Nubank

### ISSUE THREAD

**Issue by agencia-feats** [renatomb/php_qrcode_pix#12]
No app da Nubank diz assim:   "Esse código é inválido, por isso não é possível continuar "

**Comment by renatomb** [comment]
@agencia-feats se possível compartilhar o pix copia e cola que gerou o erro para que eu possa tentar reproduzir, se preferir compartilhar no privado pode mandar no privado no telegram [r3n4t0](https://t.me/r3n4t0)
