### ISSUE TITLE
Status do pagamento

### ISSUE THREAD

**Issue by gustavocoimbradev** [renatomb/php_qrcode_pix#25]
Existe alguma forma de consultar o status do pagamento?

**Comment by vanderHobus** [comment]
Mesma dúvida aqui. Aparentemente é só para geração do QRCode de recebimento mesmo.

**Comment by renatomb** [comment]
A consulta do status do pagamento é fornecida pela API da sua instituição financeira, normalmente eles exigem o registro prévio do qrcode e cobram uma parte do valor do pix, negocie com eles.
