### ISSUE TITLE
Pix não funciona no Bradesco

### ISSUE THREAD

**Issue by ebanolopes** [renatomb/php_qrcode_pix#3]
Oi, Renato, projeto bem legal. Porém eu testei e não consegui nenhuma situação em que funcionasse, tentei até mesmo o seu link de doação: https://qrcodepix.dinheiro.tech/?doacao

Estou tentando pagar com o banco Bradesco. Ajuda ai, vale até uma doação =]

**Comment by ebanolopes** [comment]
Eu tentei no Banco do Brasil e funcionou. Estranho, não?

**Comment by renatomb** [comment]
Vou disponibilizar hoje uma atualização referente a esse problema.

**Comment by renatomb** [comment]
@ebanolopes a recomendação agora é pela obrigatoriedade do 62/05 que contém o identificador do transação. Sendo possível o uso do `***` para geração automática.

Estou atualizando os exemplos e o live demo tendo em vista que alguns bancos passaram a criticar a ausência desse campo  nos últimos dias.

Como você mencionou no issue há bancos em que isso não está causando problemas, mas outros passaram a fazê-lo recentemente. E de acordo com o [Manual de Padrões para Iniciação do Pix versão 2.2.1](https://www.bcb.gov.br/content/estabilidadefinanceira/pix/Regulamento_Pix/II-ManualdePadroesparaIniciacaodoPix.pdf) pode-se entender esse dado como obrigatório.
