### ISSUE TITLE
Erro ao utilizar caracteres especiais em certos campos

### ISSUE THREAD

**Issue by batata004** [renatomb/php_qrcode_pix#6]
Amigo essa biblioteca é muito boa, meus parabéns! Funcionou de primeira. Só estou tendo um problema: caracteres especiais. Por exemplo, se eu utilizo a linha abaixo o código PIX é gerado perfeito, porém quando tento pagá-lo pelo Nubank ele acusa erro na chave. Porém assim que substituo os caracteres especiais por X tudo funciona corretamente. Exemplo:

```
$px[26][02] = "Tesçãóé";
$px[59] = "Nóme Pêssoa";
```

Esse campo acima é o Mensagem/Descrição e é possível sim utilizar caracteres especiais pois quando gero um código PIX utilizando os aplicativos de banco, eu consigo normalmente inserir caracteres especiais e o código é gerado corretamente e pode ser pago sem erro. Será que é algum erro no CRC ao interpretar os caracteres especiais?

O mais estranho é que se eu utilizar caracteres especiais no campo abaixo tudo funciona perfeitamente:

```
$px[60] = "Florianópolis";
```

**Comment by renatomb** [comment]
Problema similar ao detalhado na issue #5 .
