### ISSUE TITLE
Setar data de validade do codigo PIX

### ISSUE THREAD

**Issue by batata004** [renatomb/php_qrcode_pix#7]
Amigo, tava lendo a documentação do BC e parece que é possível gerar o código com data de validade para pagamento (inclusive com hora). Você saberia quais campos eu teria que alterar para incluir essa data?

**Comment by renatomb** [comment]
Opa @batata004 acredito que o campo vencimento está disponível somente no qrcode dinâmico do pix. Pelo que eu entendi para fazer um pix com qr code dinâmico você deve disponibilizar um payload json em uma URL que a sua instituição de pagamentos (psp recebedor) vai buscar os dados da transação na hora do pix.
Dá uma olhada no documento [Padrões para iniciação do pix ver 3.02](https://www.bcb.gov.br/content/estabilidadefinanceira/forumpireunioes/AnexoI-PadroesParaIniciacaodoPix.pdf) e verifique com sua instituição de pagamentos quais os procedimentos para você receber pix com a geração do qr code dinâmico gerado fora do app da instituição, principalmente se é necessário solicitar algum tipo de autorização para isso e se há algum manual de implementação.

**Comment by batata004** [comment]
OBRIGADO!!!!!!
