### ISSUE TITLE
QR Code inválido tanto no site demo quanto na implementação PHP 

### ISSUE THREAD

**Issue by ronaldofl** [renatomb/php_qrcode_pix#8]
Faz algum tempo que utilizo o código PHP aqui do repositório para gerar o QR Code e sempre funcionou.
Ao fazer um teste hoje, identifiquei que o QR Code gerado não está mais sendo lido no aplicativo do Sicoob.

O mesmo teste foi feito no site da demo e tive o mesmo problema.
Segue o copia e cola gerado na página de testes da Demo onde o QR Code não funciona: 00020126450014BR.GOV.BCB.PIX0114+55329997387000205TESTE52040000530398654041.005802BR5909Motobraga6003Uba62410503***50300017BR.GOV.BCB.BRCODE01051.0.063046A0F

Seguem abaixo os dados com os quais o formulário está sendo preenchido na demo:
Chave: +5532999738700
Valor: 1.00
Beneficiario: MOTOBRAGA

**Comment by zakkenila** [comment]
Estou com o mesmo problema.. nao funciona no sicoob e tambem no bradesco.. ja testei com o codigo gerado no site de exemplo e nao funciona.

**Comment by renatomb** [comment]
Não tenho sicoob para testar aqui, poderia mandar um br code gerado no aplicativo do sicoob para a gente comparar? @ronaldofl @zakkenila ?

**Comment by ronaldofl** [comment]
@renatomb o problema realmente era o identificador como o @zakkenila comentou. Depois que alterei para 123 voltou a funcionar no Sicoob
